# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculadora.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculadora.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63\x61lculadora.proto\"\x17\n\x06Numero\x12\r\n\x05valor\x18\x01 \x01(\x02\x32\x31\n\x0b\x43\x61lculadora\x12\"\n\x0craizCuadrada\x12\x07.Numero\x1a\x07.Numero\"\x00\x62\x06proto3')
)




_NUMERO = _descriptor.Descriptor(
  name='Numero',
  full_name='Numero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valor', full_name='Numero.valor', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['Numero'] = _NUMERO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numero = _reflection.GeneratedProtocolMessageType('Numero', (_message.Message,), dict(
  DESCRIPTOR = _NUMERO,
  __module__ = 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:Numero)
  ))
_sym_db.RegisterMessage(Numero)



_CALCULADORA = _descriptor.ServiceDescriptor(
  name='Calculadora',
  full_name='Calculadora',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=46,
  serialized_end=95,
  methods=[
  _descriptor.MethodDescriptor(
    name='raizCuadrada',
    full_name='Calculadora.raizCuadrada',
    index=0,
    containing_service=None,
    input_type=_NUMERO,
    output_type=_NUMERO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULADORA)

DESCRIPTOR.services_by_name['Calculadora'] = _CALCULADORA

# @@protoc_insertion_point(module_scope)
