# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculadora_pb2 as calculadora__pb2


class CalculadoraStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.raizCuadrada = channel.unary_unary(
        '/Calculadora/raizCuadrada',
        request_serializer=calculadora__pb2.Numero.SerializeToString,
        response_deserializer=calculadora__pb2.Numero.FromString,
        )


class CalculadoraServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def raizCuadrada(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'raizCuadrada': grpc.unary_unary_rpc_method_handler(
          servicer.raizCuadrada,
          request_deserializer=calculadora__pb2.Numero.FromString,
          response_serializer=calculadora__pb2.Numero.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculadora', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
